# Kiwi8 ROM Profiles Database

# Format: [0xSHA256] followed by quirk settings

[22ca535175f53fd0c8c0295b77198d7830a9c44b81497f14ee1fbc6c1322adc0]
name=Blinky [Hans Christian Egeberg, 1991].ch8
load_store_quirk=1
shift_quirk=1
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=1
hwrap=0

[00bb7001de52b562d98357d33375406c6d0308466d7d95c2580537d2451a75cd]
name=Space Invaders [David Winter].ch8
load_store_quirk=0
shift_quirk=0
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=0
hwrap=1

[cfc1c1948c4419c3d45d98d8704885d8a0bc84d0d32022e069ac9119febe6035]
name=Astro Dodge [Revival Studios, 2008].ch8
load_store_quirk=1
shift_quirk=1
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=1
hwrap=0

[871349b9cac53b5f99aabd3e25a71ad9979b85f1e7664049ad62fe288d1a0557]
name=Connect 4 [David Winter].ch8
load_store_quirk=1
shift_quirk=1
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=1
hwrap=0

[4f0b0ea0ca8cb819574dd1bef22943dd04282e005647f9dcfd9246d4e2458a89]
name=Hidden [David Winter, 1996].ch8
load_store_quirk=1
shift_quirk=1
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=1
hwrap=0

[4a07eed424eb5bbea779386f1c600f61ec7f6125539f64e4073cae2aeba7c039]
name=Tic-Tac-Toe [David Winter].ch8
load_store_quirk=1
shift_quirk=1
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=1
hwrap=0

[f6024fea49433bb48b05fa05f7ab1d80696684d7cd89f884315494ed08fa4f22]
name=Stars [Sergey Naydenov, 2010].ch8
load_store_quirk=1
shift_quirk=1
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=1
hwrap=0

[c435e310ed832846a10f6d19e103910400a97dce27745370cb18207f24baee39]
name=Brix [Andreas Gustafsson, 1990].ch8
load_store_quirk=0
shift_quirk=0
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=0
hwrap=1

[281d3bcc61227e15a5d3294b0e10facc156ec1bd819a3018d92e3ccf3a07acf1]
name=UFO [Lutz V, 1992].ch8
load_store_quirk=0
shift_quirk=0
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=0
hwrap=1

[c37c9f76fa1061e1eb15e66ad76536798c84024bd67a64735cc454de0857f889]
name=Animal Race [Brian Astle].ch8
load_store_quirk=0
shift_quirk=1
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=1
hwrap=0
