# Kiwi8 ROM Profiles Database

# Format: [0xCRC32] followed by quirk settings

[0x9D307E90]
name=Blinky [Hans Christian Egeberg, 1991].ch8
load_store_quirk=1
shift_quirk=1
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=1
hwrap=0

[0x6FF0A017]
name=Space Invaders [David Winter].ch8
load_store_quirk=0
shift_quirk=0
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=0
hwrap=1

[0x614BA7F]
name=Astro Dodge [Revival Studios, 2008].ch8
load_store_quirk=1
shift_quirk=1
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=1
hwrap=0

[0x9858889B]
name=Connect 4 [David Winter].ch8
load_store_quirk=1
shift_quirk=1
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=1
hwrap=0

[0x61861AE5]
name=Hidden [David Winter, 1996].ch8
load_store_quirk=1
shift_quirk=1
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=1
hwrap=0

[0x3A297A10]
name=Tic-Tac-Toe [David Winter].ch8
load_store_quirk=1
shift_quirk=1
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=1
hwrap=0

[0x511CDD7A]
name=Stars [Sergey Naydenov, 2010].ch8
load_store_quirk=1
shift_quirk=1
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=1
hwrap=0

[0xAAA44D0B]
name=Brix [Andreas Gustafsson, 1990].ch8
load_store_quirk=0
shift_quirk=0
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=0
hwrap=1

[0x331413E7]
name=UFO [Lutz V, 1992].ch8
load_store_quirk=0
shift_quirk=0
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=0
hwrap=1

[0x6465ACEF]
name=Animal Race [Brian Astle].ch8
load_store_quirk=0
shift_quirk=1
jump_quirk=0
logic_vf_quirk=0
i_overflow_quirk=0
draw_flag_quirk=0
vwrap=1
hwrap=0
