name: Lint

on:
  pull_request: {}

jobs:
  shared-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run forbidden tokens linter
        run: |
          bash tools/check_forbidden_tokens.sh shared
