name: Release

on:
  release:
    types: [published]

jobs:

  build:
    uses: ./.github/workflows/build-reusable.yml

  upload-macos:
    needs: build
    runs-on: macos-15
    strategy:
      matrix:
        arch: [x86_64, ARM64]
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: Kiwi8-${{ github.ref_name }}-macOS-${{ matrix.arch }}
          path: .

      - name: Restore executable permissions
        run: |
          chmod -R u=rwx,go=rx Kiwi8.app

      - name: Create macOS release archive
        run: |
          ditto -c -k --sequesterRsrc --keepParent Kiwi8.app Kiwi8-${{ github.ref_name }}-macOS-${{ matrix.arch }}.zip

      - name: Upload macOS build to Release
        uses: softprops/action-gh-release@v2
        with:
          files: Kiwi8-${{ github.ref_name }}-macOS-${{ matrix.arch }}.zip

  upload-windows:
    needs: build
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x86_64, ARM64]
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: Kiwi8-${{ github.ref_name }}-Windows-${{ matrix.arch }}
          path: .

      - name: Create Windows release archive
        shell: powershell
        run: |
          Compress-Archive -Path * -DestinationPath Kiwi8-${{ github.ref_name }}-Windows-${{ matrix.arch }}.zip

      - name: Upload Windows build to Release
        uses: softprops/action-gh-release@v2
        with:
          files: Kiwi8-${{ github.ref_name }}-Windows-${{ matrix.arch }}.zip

  upload-linux:
    needs: build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [x86_64, ARM64]
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: Kiwi8-${{ github.ref_name }}-Linux-${{ matrix.arch }}
          path: linux_release

      - name: Create Linux release archive
        run: |
          tar czf Kiwi8-${{ github.ref_name }}-Linux-${{ matrix.arch }}.tar.gz -C linux_release .

      - name: Upload Linux build to Release
        uses: softprops/action-gh-release@v2
        with:
          files: Kiwi8-${{ github.ref_name }}-Linux-${{ matrix.arch }}.tar.gz
